//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_GrabObjectR;
        
        private static SteamVR_Action_Boolean p_default_GrabMoveR;
        
        private static SteamVR_Action_Boolean p_default_LaserActivate;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabMoveL;
        
        private static SteamVR_Action_Boolean p_default_GrabObjectL;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Boolean default_GrabObjectR
        {
            get
            {
                return SteamVR_Actions.p_default_GrabObjectR.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabMoveR
        {
            get
            {
                return SteamVR_Actions.p_default_GrabMoveR.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_LaserActivate
        {
            get
            {
                return SteamVR_Actions.p_default_LaserActivate.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabMoveL
        {
            get
            {
                return SteamVR_Actions.p_default_GrabMoveL.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabObjectL
        {
            get
            {
                return SteamVR_Actions.p_default_GrabObjectL.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_GrabObjectR,
                    SteamVR_Actions.default_GrabMoveR,
                    SteamVR_Actions.default_LaserActivate,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabMoveL,
                    SteamVR_Actions.default_GrabObjectL,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_GrabObjectR,
                    SteamVR_Actions.default_GrabMoveR,
                    SteamVR_Actions.default_LaserActivate,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabMoveL,
                    SteamVR_Actions.default_GrabObjectL};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_GrabObjectR,
                    SteamVR_Actions.default_GrabMoveR,
                    SteamVR_Actions.default_LaserActivate,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabMoveL,
                    SteamVR_Actions.default_GrabObjectL};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_GrabObjectR,
                    SteamVR_Actions.default_GrabMoveR,
                    SteamVR_Actions.default_LaserActivate,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabMoveL,
                    SteamVR_Actions.default_GrabObjectL};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_GrabObjectR = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabObjectR")));
            SteamVR_Actions.p_default_GrabMoveR = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabMoveR")));
            SteamVR_Actions.p_default_LaserActivate = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/LaserActivate")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabMoveL = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabMoveL")));
            SteamVR_Actions.p_default_GrabObjectL = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabObjectL")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
