//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabObjectR
        {
            get
            {
                return SteamVR_Actions.default_GrabObjectR;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabMoveR
        {
            get
            {
                return SteamVR_Actions.default_GrabMoveR;
            }
        }
        
        public virtual SteamVR_Action_Boolean LaserActivate
        {
            get
            {
                return SteamVR_Actions.default_LaserActivate;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabMoveL
        {
            get
            {
                return SteamVR_Actions.default_GrabMoveL;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabObjectL
        {
            get
            {
                return SteamVR_Actions.default_GrabObjectL;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
